---
# tasks file for test_handlers

- name: Before handler
  ansible.builtin.command:
    cmd: 'echo "Before handler!"'
  changed_when: true
  notify: "notify handler"

- name: After flush
  ansible.builtin.command:
    cmd: 'echo "After flush!"'
  changed_when: true
